version: v1beta

plugins:
  - TestcontainersDinD@v1

variables:
  - VERSION
  - COMMIT

targets:
  src/dotnet-testcontainers.csproj:
    type: [build, test]
    with:
      base: mcr.microsoft.com/dotnet/sdk:10.0