version: 2
updates:
  - package-ecosystem: "helm"
    directory: "/charts/buildcharts"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
