apiVersion: v2
description: A helm chart for dotnet
maintainers:
- name: Eddie Tisma
  url: https://github.com/buildcharts/charts/
name: dotnet-docker
sources:
- https://github.com/buildcharts/charts/blob/main/dotnet/docker/
type: library
version: 0.0.2
