version: latest

environment:
  - VERSION
  - COMMIT

targets:
  krp.sln:
    type: build
    with:
      base: mcr.microsoft.com/dotnet/sdk:9.0

  src/dotnet-krp/dotnet-krp.csproj:
    type: nuget

  src/Krp/Krp.csproj:
    type: [nuget, docker]
    with:
      base: mcr.microsoft.com/dotnet/aspnet:9.0
      tags: ["docker.io/username/krp:${VERSION}.${COMMIT}"]

  test/Krp.Tests/Krp.Tests.csproj:
    type: test

  test/Krp.Tests1/Krp.Tests1.csproj:
    type: test


