# Parse latest TRX generated by BuildCharts test output for a sample.
param(
  [string]$TestOutputDirectory
)

$latestTrxFile = Get-ChildItem -Path $testOutputDirectory -Recurse -Filter *.trx -File -ErrorAction SilentlyContinue |
  Sort-Object LastWriteTime -Descending |
  Select-Object -First 1

if (-not $latestTrxFile) {
  Write-Warning "No .trx file found under $testOutputDirectory"
  exit 0
}

Write-Host "Latest test result: $($latestTrxFile.FullName)" -ForegroundColor Green

try {
  [xml]$trx = Get-Content -Path $latestTrxFile.FullName

  $summary = $trx.TestRun.ResultSummary
  $counters = $summary.Counters
  if ($null -ne $counters) {
    Write-Host (
      "Total={0} Passed={1} Failed={2} Skipped={3}" -f
      $counters.total,
      $counters.passed,
      $counters.failed,
      $counters.notExecuted
    ) -ForegroundColor Cyan
  }

  $allResults = @($trx.TestRun.Results.UnitTestResult)
  $failedResults = $allResults | Where-Object { $_.outcome -eq "Failed" }

  if ($failedResults.Count -gt 0) {
    Write-Host "Failed tests:" -ForegroundColor Yellow
    $failedResults | ForEach-Object { Write-Host " - $($_.testName)" -ForegroundColor Yellow }
  }
  else {
    Write-Host "No failed tests found in TRX." -ForegroundColor Green
  }
}
catch {
  Write-Warning "Failed to parse TRX summary: $($_.Exception.Message)"
}
