version: v1beta

variables:
  - VERSION
  - COMMIT

targets:
  src/dotnet-test.csproj:
    - type: build
      with:
        contexts:
          base: docker-image://mcr.microsoft.com/dotnet/sdk:10.0
    - type: test
      with:
        contexts:
          base: docker-image://mcr.microsoft.com/dotnet/sdk:10.0
